import {CarpenterModel, CarpenterModelRelationship, DataTypes } from "../../../index.js";
import bcrypt from 'bcrypt';

//This is used to hash passwords during the seeding process. Inserting during normal operations should be done in the Password Change functions.
const saltRounds = 10;
const hashPassword = (password) => {
    return bcrypt.hashSync(password, saltRounds);
};
export default class Person extends CarpenterModel {

    static sequelizeDefinition = {
        person_id: { type: DataTypes.UUID, primaryKey: true, allowNull: false, },
        name: { type: DataTypes.STRING, allowNull: false, },
        title: { type: DataTypes.STRING, allowNull: true, },
        organization_name: { type: DataTypes.STRING, allowNull: true, }, // This is the name of the organization that this person is associated with.
        email: { type: DataTypes.STRING, allowNull: false, unique: true },
        phone: { type: DataTypes.STRING, allowNull: false, unique: true },
        sms: { type: DataTypes.STRING, allowNull: false, unique: true },
        email: { type: DataTypes.STRING, allowNull: false, unique: true },
        description: { type: DataTypes.STRING, allowNull: true, },
        organization_id: { type: DataTypes.UUID, allowNull: false, }, // This is the organization that is identifying this person.
    }

    static sequelizeConnections = [
        new CarpenterModelRelationship({
            connectionType: "1M",
            parentModelName: "Organization",
            required: true, childParentKey: 'organization_id', childModelName: "Person"
        }),
    ];

    static seedDataCore = [
        {
            person_id: "a1b2c3d4-e5f6-7g8h-9i0j-1k2l3m4n5o6p",
            name: "John Doe",
            title: "Default Administrator",
            organization_name: "Tech Solutions Inc.",
            phone: "+1234567890",
            sms: "+1234567890",
            description: "A skilled software engineer with a passion for developing innovative solutions.",
            email: "john.doe@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        
    ];
    static seedDataDemo = [
        {
            person_id: "b2c3d4e5-f6g7-8h9i-0j1k-2l3m4n5o6p7q",
            name: "Jane Smith",
            title: "Project Manager",
            organization_name: "Global Innovations Ltd.",
            phone: "+1234567891",
            sms: "+1234567891",
            description: "Experienced project manager leading cross-functional teams to success.",
            email: "jane.smith@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "c3d4e5f6-g7h8-9i0j-1k2l-3m4n5o6p7q8r",
            name: "Michael Johnson",
            title: "Data Analyst",
            organization_name: "Insight Analytics",
            phone: "+1234567892",
            sms: "+1234567892",
            description: "Data-driven analyst with expertise in visualization and business intelligence.",
            email: "michael.johnson@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "d4e5f6g7-h8i9-0j1k-2l3m-4n5o6p7q8r9s",
            name: "Emily Davis",
            title: "UX Designer",
            organization_name: "Creative Minds Studio",
            phone: "+1234567893",
            sms: "+1234567893",
            description: "Designer focused on creating intuitive and delightful user experiences.",
            email: "emily.davis@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "e5f6g7h8-i9j0-1k2l-3m4n-5o6p7q8r9s0t",
            name: "David Wilson",
            title: "Systems Administrator",
            organization_name: "SecureNet Corp.",
            phone: "+1234567894",
            sms: "+1234567894",
            description: "Reliable sysadmin ensuring system uptime and network security.",
            email: "david.wilson@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "f6g7h8i9-j0k1-2l3m-4n5o-6p7q8r9s0t1u",
            name: "Sarah Brown",
            title: "Marketing Specialist",
            organization_name: "BrightWave Marketing",
            phone: "+1234567895",
            sms: "+1234567895",
            description: "Creative marketer skilled in digital campaigns and brand growth.",
            email: "sarah.brown@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "g7h8i9j0-k1l2-3m4n-5o6p-7q8r9s0t1u2v",
            name: "Christopher Lee",
            title: "DevOps Engineer",
            organization_name: "CloudOps Solutions",
            phone: "+1234567896",
            sms: "+1234567896",
            description: "Engineer bridging development and operations with CI/CD pipelines.",
            email: "christopher.lee@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "h8i9j0k1-l2m3-4n5o-6p7q-8r9s0t1u2v3w",
            name: "Olivia Martinez",
            title: "HR Manager",
            organization_name: "PeopleFirst HR",
            phone: "+1234567897",
            sms: "+1234567897",
            description: "HR professional fostering talent development and employee engagement.",
            email: "olivia.martinez@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "i9j0k1l2-m3n4-5o6p-7q8r-9s0t1u2v3w4x",
            name: "James Anderson",
            title: "Business Analyst",
            organization_name: "NextGen Consulting",
            phone: "+1234567898",
            sms: "+1234567898",
            description: "Analyst bridging the gap between business needs and technology solutions.",
            email: "james.anderson@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "j0k1l2m3-n4o5-6p7q-8r9s-0t1u2v3w4x5y",
            name: "Sophia Thomas",
            title: "Financial Advisor",
            organization_name: "WealthGuard Advisors",
            phone: "+1234567899",
            sms: "+1234567899",
            description: "Advisor helping clients achieve long-term financial security.",
            email: "sophia.thomas@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "k1l2m3n4-o5p6-7q8r-9s0t-1u2v3w4x5y6z",
            name: "Daniel Taylor",
            title: "Cybersecurity Specialist",
            organization_name: "SafeNet Security",
            phone: "+1234567800",
            sms: "+1234567800",
            description: "Expert in identifying and mitigating security threats.",
            email: "daniel.taylor@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "l2m3n4o5-p6q7-8r9s-0t1u-2v3w4x5y6z7a",
            name: "Ava Hernandez",
            title: "Content Writer",
            organization_name: "Creative Copy Co.",
            phone: "+1234567801",
            sms: "+1234567801",
            description: "Writer crafting engaging content that connects with audiences.",
            email: "ava.hernandez@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "m3n4o5p6-q7r8-9s0t-1u2v-3w4x5y6z7a8b",
            name: "Matthew Moore",
            title: "AI Researcher",
            organization_name: "FutureTech Labs",
            phone: "+1234567802",
            sms: "+1234567802",
            description: "Researcher exploring artificial intelligence and machine learning frontiers.",
            email: "matthew.moore@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "n4o5p6q7-r8s9-0t1u-2v3w-4x5y6z7a8b9c",
            name: "Isabella Clark",
            title: "Graphic Designer",
            organization_name: "Visionary Designs",
            phone: "+1234567803",
            sms: "+1234567803",
            description: "Designer bringing ideas to life through creative visuals.",
            email: "isabella.clark@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "o5p6q7r8-s9t0-1u2v-3w4x-5y6z7a8b9c0d",
            name: "Ethan Lewis",
            title: "Mechanical Engineer",
            organization_name: "Innovatech Engineering",
            phone: "+1234567804",
            sms: "+1234567804",
            description: "Engineer specializing in innovative mechanical systems.",
            email: "ethan.lewis@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "p6q7r8s9-t0u1-2v3w-4x5y-6z7a8b9c0d1e",
            name: "Mia Walker",
            title: "Product Manager",
            organization_name: "NextWave Products",
            phone: "+1234567805",
            sms: "+1234567805",
            description: "Product leader guiding teams from vision to execution.",
            email: "mia.walker@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "q7r8s9t0-u1v2-3w4x-5y6z-7a8b9c0d1e2f",
            name: "Benjamin Hall",
            title: "Network Engineer",
            organization_name: "ConnectPro Networks",
            phone: "+1234567806",
            sms: "+1234567806",
            description: "Engineer maintaining reliable and high-performance networks.",
            email: "benjamin.hall@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "r8s9t0u1-v2w3-4x5y-6z7a-8b9c0d1e2f3g",
            name: "Charlotte Allen",
            title: "Operations Manager",
            organization_name: "Streamline Ops",
            phone: "+1234567807",
            sms: "+1234567807",
            description: "Manager optimizing operations and driving efficiency.",
            email: "charlotte.allen@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "s9t0u1v2-w3x4-5y6z-7a8b-9c0d1e2f3g4h",
            name: "Henry Young",
            title: "Legal Advisor",
            organization_name: "TrustLaw Associates",
            phone: "+1234567808",
            sms: "+1234567808",
            description: "Advisor providing strategic legal guidance.",
            email: "henry.young@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "t0u1v2w3-x4y5-6z7a-8b9c-0d1e2f3g4h5i",
            name: "Amelia King",
            title: "Sales Executive",
            organization_name: "MarketReach Ltd.",
            phone: "+1234567809",
            sms: "+1234567809",
            description: "Sales professional building relationships and driving revenue.",
            email: "amelia.king@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "u1v2w3x4-y5z6-7a8b-9c0d-1e2f3g4h5i6j",
            name: "Alexander Scott",
            title: "IT Consultant",
            organization_name: "TechAdvisors Group",
            phone: "+1234567810",
            sms: "+1234567810",
            description: "Consultant helping businesses align IT with strategic goals.",
            email: "alexander.scott@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "v2w3x4y5-z6a7-8b9c-0d1e-2f3g4h5i6j7k",
            name: "Harper Green",
            title: "Recruiter",
            organization_name: "TalentMatch Agency",
            phone: "+1234567811",
            sms: "+1234567811",
            description: "Recruiter connecting top talent with great opportunities.",
            email: "harper.green@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "w3x4y5z6-a7b8-9c0d-1e2f-3g4h5i6j7k8l",
            name: "Elijah Baker",
            title: "Cloud Architect",
            organization_name: "SkyHigh Cloud Services",
            phone: "+1234567812",
            sms: "+1234567812",
            description: "Architect designing scalable and secure cloud infrastructures.",
            email: "elijah.baker@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        },
        {
            person_id: "x4y5z6a7-b8c9-0d1e-2f3g-4h5i6j7k8l9m",
            name: "Abigail Perez",
            title: "Customer Success Manager",
            organization_name: "ClientFirst Solutions",
            phone: "+1234567813",
            sms: "+1234567813",
            description: "Manager ensuring customers achieve success with their solutions.",
            email: "abigail.perez@example.com",
            organization_id: "94a72a62-3d66-4e78-a20a-14f4eae1a9de",
        }
    ]
};
